---
title: "sow_subcontractor"
output: html_document
---

#### Application to Subcontractors
The `r prime_vs_sub` shall flow down CSDR requirements referenced in section `r cost_rep_sow_numb` and its sub-paragraphs to subcontractors (regardless of subcontractor tier) when the subcontract value is expected to exceed \$20 million using the maximum allowable contract quantities, hours, or options (as applicable), as required by Department of Defense Manual (DoDM) 5000.04 - CSDR Manual. Subcontractors that meet the CSDR flow-down requirement are refered to as "direct reporting subcontractors". The Contractor shall require direct reporting subcontractors to electronically submit CSDRs deliverables directly to the Defense Cost and Resource Center (DCARC). The Contractor shall ensure that direct reporting subcontractors collect data in sufficient detail to meet Attachment `r CSDR_plan_attch_numb` - CSDR Plan and DoDM 5000.04 - CSDR Manual requirements. The Contractor shall collect and deliver data on all subcontractors to comply with Attachment `r RDT_attach_numb` and CDRL `r RDT_CDRL_numb` - Resource Distribution Table and Attachment `r CSDR_plan_attch_numb` - CSDR Plan requirements. A “subcontract” is any agreement, purchase order, or instrument other than a prime contract calling for work or for the material required for the performance of one or more prime contracts. A “subcontract” usually covers procurement of major components or subsystems that require the subcontractor to do extensive design, development, engineering, and testing to meet a prime contractor’s procurement specifications or performs work on behalf of the prime contractor in order to complete the prime contractor’s scope of work requirements.  
