---
title: "Cost and Hour Report (FlexFile) CDRL"
output:
  word_document: default
  html_document:
    df_print: paged
version: 0.1.0
---

A. CONTRACT LINE ITEM NO.........: `r params_from_excel$cdrl_clin_numb`  
B. EXHIBIT.......................: `r params_from_excel$cdrl_exhibit`  
C. CATEGORY......................: Other.  
D. SYSTEM/ITEM...................: `r params_from_excel$prime_mission_product`  
E. CONTRACT/PR NUMBER............: `r params_from_excel$contract_numb`  
F. CONTRACTOR....................: `r params_from_excel$contractor_name`  
G. PREPARED BY...................: `r params_from_excel$cdrl_prepared_by`  
H. DATE..........................: `r params_from_excel$cdrl_prepared_date`  
I. APPROVED BY...................: `r params_from_excel$cdrl_approved_by`  
J. DATE..........................: `r params_from_excel$cdrl_approved_date`  
01. DATA ITEM NUMBER.............: `r params_from_excel$FlexFile_CDRL_numb`  
02. TITLE OF DATA ITEM...........: `r FlexFile_CDRL_title`  
03. SUBTITLE ....................: `r FlexFile_CDRL_subtitle`  
04. AUTHORITY....................: `r FlexFile_CDRL_did`(T) and see Block 16.  
05. CONTRACT REFERENCE...........:   
06. REQUIRING OFFICE.............: `r params_from_excel$program_office_name_abbr`  
07. DD 250 REQ...................: See Block 16.  
08. APPROVAL CODE................: None.  
09. DIST. STATEMENT REQUIRED.....: `r FlexFile_CDRL_dist`  
10. FREQUENCY....................: See Block 16.  
11. AS OF DATE...................: See Block 16.  
12. DATE OF FIRST SUBMISSION.....: See Block 16.  
13. DATE OF SUBSEQUENT SUBMISSION: See Block 16.  
14. DISTRIBUTION.................: See Block 16.  
15. TOTAL........................: See Attachment `r params_from_excel$CSDR_plan_attch_numb` - CSDR Plan.  
16. REMARKS......................:  

Block 04: The `r prime_vs_sub` shall develop, maintain, and deliver the data item in accordance with `r FlexFile_CDRL_did`, the CSDR Manual (DoD 5000.04-M-1), and as tailored in this CDRL and Attachment `r params_from_excel$CSDR_plan_attch_numb` - CSDR Plan. The CSDR Manual is available from the CADE website at https://cade.osd.mil/.  

The `r prime_vs_sub` shall deliver this data item in one of the following formats: a) a stand-alone Microsoft Excel file (file extension ".xlsx"), b) a comma separated values (file extension ".csv") so long as the Excel or comma separated values submission fulfills the requirements of the DD FORM 2794 and is in accordance with the FlexFile DID (`r FlexFile_CDRL_did`), or c) JavaScript Object Notation (JSON) as described in the FlexFile File Format Specification (FFS) and Data Exchange Instructions (DEI) referenced in the FlexFile DID (`r FlexFile_CDRL_did`) Requirements Section 2. The FlexFile FFS and DEI are available at the CADE website at https://cade.osd.mil/policy then selecting "Data Item Descriptions and Forms".  

Block 07: The DCARC office will issue a letter stating if the submission to the DCARC website has been accepted or rejected. Deliverables will be reviewed for technical content and/or format. Should the Government require the data item to be corrected after its delivery the `r prime_vs_sub` shall resubmit an update within 15 calendar days after receipt of Government comments.  

Block 10, 11, 12, and 13: The `r prime_vs_sub` shall submit reports at frequencies specified in Attachment `r params_from_excel$CSDR_plan_attch_numb` - CSDR Plan.  

Block 14: The `r prime_vs_sub` shall submit files electronically using the CADE website. Data submitters shall register through the CADE website and possess a DoD-approved ECA digital certificate or DoD-issued CAC to obtain a CADE Portal account and be authorized to upload CSDR content. Users can obtain access by submitting user information about themselves and their organizations to the CADE Portal and requesting a CSDR submitter user role. After the registration information has been verified, CAPE shall authorize the user account and requested roles. All CADE Portal accounts shall be renewed at least annually.  

`r params_from_excel$submission_instructions`  

17. PRICE GROUP..................: N/A
18. ESTIMATED TOTAL PRICE........: N/A
